language: csharp
sudo: required
dist: xenial # Ubuntu 16.04

dotnet : 2.1.508

addons:
  apt:
    packages:
      - build-essential
      - ruby
      - ruby-dev
      - rubygems-integration

before_install:
  - gem install --no-ri --no-rdoc fpm 
  
  #- wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
  #- sudo dpkg -i packages-microsoft-prod.deb
  #- sudo apt-get install apt-transport-https -y
  #- sudo apt-get update -y
  #- sudo apt-get install dotnet-sdk-2.1=2.1.505* -y

env:
 - FAKE_DETAILED_ERRORS=true HOME=/home/travis APPDATA=/home/travis LocalAppData=/home/travis


mono:
  - 5.18.1

script: 
  - dotnet build build.proj /nologo /verbosity:minimal /p:Parallel=true

branches:
  except:
    - gh-pages
