version: 2
general:
  branches:
    ignore:
      - gh-pages # list of branches to ignore
      
jobs:
  build:
    working_directory: /build
    docker:
      - image: mono:5.18.1
    steps:
      # Workaround from https://discuss.circleci.com/t/failed-to-fetch-debian/29258/2
      - run:
          name: fixup
          command: |
            rm /etc/apt/sources.list
            echo "deb http://archive.debian.org/debian/ jessie-backports main" | tee -a /etc/apt/sources.list
            echo "deb-src http://archive.debian.org/debian/ jessie-backports main" | tee -a /etc/apt/sources.list
            echo "deb http://cdn-fastly.deb.debian.org/debian/ jessie main" | tee -a /etc/apt/sources.list
            echo "deb-src http://cdn-fastly.deb.debian.org/debian/ jessie main" | tee -a /etc/apt/sources.list
            echo "deb http://security.debian.org/ jessie/updates main" | tee -a /etc/apt/sources.list
            echo "deb-src http://security.debian.org/ jessie/updates main" | tee -a /etc/apt/sources.list
            echo "Acquire::Check-Valid-Until false;" | tee -a /etc/apt/apt.conf.d/10-nocheckvalid
            echo 'Package: *\nPin: origin "archive.debian.org"\nPin-Priority: 500' | tee -a /etc/apt/preferences.d/10-archive-pin
            apt-get update
            apt-get install -y openssh-client git

      - checkout
      - run:
          name: install-fake
          command: |
            apt-get update
            apt-get install -y libunwind8 libicu52 unzip wget git
            wget https://github.com/fsharp/FAKE/releases/download/5.16.0/fake-dotnetcore-linux-x64.zip -O /tmp/fake-dotnetcore-linux-x64.zip
            mkdir fake-dotnetcore
            unzip /tmp/fake-dotnetcore-linux-x64.zip -d fake-dotnetcore || echo unzip returned $?
            chmod +x $PWD/fake-dotnetcore/fake
      - run:
          name: build-project
          command: |
            export TERM=xterm-256color
            export PATH=$PATH:$PWD/fake-dotnetcore/
            export MSBUILDDISABLENODEREUSE=1
            export BuildInParallel=false
            fake run build.fsx --parallel 3